#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Dec 24 13:42:00 2023

@author: prakashgawas
"""
import numpy as np
config = {
          101 : {'policy': 'xgb',
               'search_files': False,
               'runs' : 1,                    
               'objective' : 'reg:absoluteerror',
               'eval_metric': 'rmse',
               'ext': 'reg_abs_norm_cum_calls_made' ,
               'normalize' : True,
               'action_type' : 'max',
               'type': 'reg',
               'target':'cum_calls_made',
               'train' : False,
               'fit': False     ,
               'criteria': 'add_direct',
               'prob_threshold': None,
               'features':  ['t_rem', 'delay_bucket_1', 'delay_bucket_2',
                             'delay_bucket_3', 'delay_bucket_4', 'delay_bucket_5', 'delay_bucket_6', 
                             'time_since_last_call', 'shifts_available', 'last_response',
                             'sum_cutoff_at_start' , 'last_calls', 'time_by_shifts_available' ,'cum_calls_made_0.9'],
               },
          
          
          201 : {'policy': 'corn',
               'search_files': False,   
               'runs' : 1,
               'ext': 'class_corn_0.5' ,
               'learning_rate': 0.001,
               'wt':1000,
               'normalize' : True,
               'type': 'class',
               'target': 'best_action',
               'action_type' : 'threshold',
               'fit': False,
               
               'prob_threshold': 0.5,
               'features':  ['t_rem', 'delay_bucket_1', 'delay_bucket_2',
                             'delay_bucket_3', 'delay_bucket_4', 'delay_bucket_5',
                             'delay_bucket_6', 'time_since_last_call', 'shifts_available', 
                             'sum_cutoff_at_start' , 'last_calls', 'time_by_shifts_available' ,'last_response',
                             'cum_calls_made_at_start','cum_calls_made_0.9'],
               },#},
              
              
              
              202 : {'policy': 'corn',
                   'search_files': False,
                   'runs' : 1,
                   'ext': 'class_corn_0.4' ,
                   'learning_rate': 0.001,
                   'normalize' : True,
                   'wt':1000,
                   'type': 'class',
                   'target': 'best_action',
                   'action_type' : 'threshold',
                   'fit': False,
                   
                   'prob_threshold': 0.4,
                   'features':  ['t_rem', 'delay_bucket_1', 'delay_bucket_2',
                                 'delay_bucket_3', 'delay_bucket_4', 'delay_bucket_5',
                                 'delay_bucket_6', 'time_since_last_call', 'shifts_available', 
                                 'sum_cutoff_at_start' , 'last_calls', 'time_by_shifts_available' ,'last_response',
                                 'cum_calls_made_at_start','cum_calls_made_0.9'],
                   },
              
                        
          203 : {'policy': 'corn',
               'search_files': False,
               'runs' : 1,
               'ext': 'class_corn_0.6' ,
               'wt':1000,
               'learning_rate': 0.001,
               'normalize' : True,
               'type': 'class',
               'target': 'best_action',
               'action_type' : 'threshold',
               'fit': False,
               
               'prob_threshold': 0.6,
               'features':  ['t_rem', 'delay_bucket_1', 'delay_bucket_2',
                             'delay_bucket_3', 'delay_bucket_4', 'delay_bucket_5',
                             'delay_bucket_6', 'time_since_last_call', 'shifts_available', 
                             'sum_cutoff_at_start' , 'last_calls', 'time_by_shifts_available' ,'last_response',
                             'cum_calls_made_at_start','cum_calls_made_0.9'],
               },
              
              
             102 : {'policy': 'xgb',
                   'search_files': False,
                   'runs' : 1,
                   'objective' : 'reg:squarederror',
                   'eval_metric': 'rmse',
                   'ext': 'reg_abs_norm_mse' ,
                   'type': 'reg',
                   'target': 'best_action',
                   'action_type' : 'round',
                   'normalize' : True,
                   'prob_threshold': None,
                   'fit': False,
                   'criteria': 'check_obj',
                   'features':  ['t_rem', 'delay_bucket_1', 'delay_bucket_2',
                                 'delay_bucket_3', 'delay_bucket_4', 'delay_bucket_5', 'delay_bucket_6', 
                                 'time_since_last_call', 'shifts_available', 
                                 'sum_cutoff_at_start' , 'last_calls', 'time_by_shifts_available' ,'last_response',
                                 'cum_calls_made_at_start','cum_calls_made_0.9'],

                   },#
          
          

          
          103 :     {'policy': 'xgb',
                         'search_files': False,
                         'runs' : 1,
                         'objective' : 'multi:softprob',
                         'eval_metric': 'rmse',
                         'ext': 'class_abs_norm_softprob' ,
                         'normalize' : True,
                         'action_type': 'max',
                         'type': 'class',
                         'target': 'best_action',
                         'prob_threshold': None,
                         'fit': False,
                         'criteria': 'check_obj',
                         'features':  ['t_rem', 'delay_bucket_1', 'delay_bucket_2',
                                       'delay_bucket_3', 'delay_bucket_4', 'delay_bucket_5', 'delay_bucket_6', 
                                       'time_since_last_call', 'shifts_available', 'last_response',
                                       'sum_cutoff_at_start' , 'last_calls', 'time_by_shifts_available' ,
                                       'cum_calls_made_at_start','cum_calls_made_0.9'],

                         },
          
          104 :   {'policy': 'xgb',
                         'search_files': False,
                         'runs' : 1,
                         'objective' : 'multi:softprob',
                         'eval_metric': 'rmse',
                         'ext': 'class_abs_norm_softprob_mean' ,
                         'action_type' : 'mean',
                         'normalize' : True,
                         'type': 'class',
                         'target': 'best_action',
                         'prob_threshold': None,
                         'fit': False,
                         'criteria': 'check_obj',
                         'features':  ['t_rem', 'delay_bucket_1', 'delay_bucket_2',
                                       'delay_bucket_3', 'delay_bucket_4', 'delay_bucket_5', 'delay_bucket_6', 
                                       'time_since_last_call', 'shifts_available', 
                                       'sum_cutoff_at_start' , 'last_calls', 'time_by_shifts_available' ,'last_response',
                                       'cum_calls_made_at_start','cum_calls_made_0.9'],

                         },
          
          105 :      {'policy': 'xgb',
                             'search_files': False,
                             'runs' : 1,
                             'objective' : 'multi:softprob',
                             'eval_metric': 'rmse',
                             'ext': 'class_abs_norm_softprob_prob' ,
                             'action_type' : 'prob',
                             'normalize' : True,
                             'type': 'class',
                             'target': 'best_action',
                             'prob_threshold': None,
                             'fit': False,
                             'criteria': 'check_obj',
                             'features':  ['t_rem', 'delay_bucket_1', 'delay_bucket_2',
                                           'delay_bucket_3', 'delay_bucket_4', 'delay_bucket_5', 'delay_bucket_6', 
                                           'time_since_last_call', 'shifts_available', 
                                           'sum_cutoff_at_start' , 'last_calls', 'time_by_shifts_available' ,'last_response',
                                           'cum_calls_made_at_start','cum_calls_made_0.9'],

                             },
          
             106: {'policy': 'xgb',
                   'search_files': False,
                   'runs' : 1,
                   'objective' : 'multi:softprob',
                   'eval_metric': 'rmse',
                   'ext': 'class_abs_norm_softprob_quant0.6' ,
                   'prob_threshold' : 0.6,
                   'action_type' : 'quant',
                   'normalize' : True,
                   'type': 'class',
                   'target': 'best_action',
                   'fit': False,
                   'criteria': 'check_obj',
                   'features':  ['t_rem', 'delay_bucket_1', 'delay_bucket_2',
                                 'delay_bucket_3', 'delay_bucket_4', 'delay_bucket_5', 'delay_bucket_6', 
                                 'time_since_last_call', 'shifts_available', 
                                 'sum_cutoff_at_start' , 'last_calls', 'time_by_shifts_available' ,'last_response',
                                 'cum_calls_made_at_start','cum_calls_made_0.9'],

                   },
              
             107: {'policy': 'xgb',
                   'search_files': False,
                   'runs' : 1,
                   'objective' : 'multi:softprob',
                   'eval_metric': 'rmse',
                   'ext': 'class_abs_norm_softprob_quant0.5' ,
                   'prob_threshold' : 0.5,
                   'action_type' : 'quant',
                   'normalize' : True,
                   'type': 'class',
                   'target': 'best_action',
                   'fit': False,
                   'criteria': 'check_obj',
                   'features':  ['t_rem', 'delay_bucket_1', 'delay_bucket_2',
                                 'delay_bucket_3', 'delay_bucket_4', 'delay_bucket_5', 'delay_bucket_6', 
                                 'time_since_last_call', 'shifts_available', 
                                 'sum_cutoff_at_start' , 'last_calls', 'time_by_shifts_available' ,'last_response',
                                 'cum_calls_made_at_start','cum_calls_made_0.9'],

                   },
              
              108: {'policy': 'xgb',
                   'search_files': False,
                   'runs' : 1,
                   'objective' : 'multi:softprob',
                   'eval_metric': 'rmse',
                   'ext': 'class_abs_norm_softprob_quant0.4' ,
                   'prob_threshold' : 0.4,
                   'action_type' : 'quant',
                   'normalize' : True,
                   'type': 'class',
                   'target': 'best_action',
                   'fit': False,
                   'criteria': 'check_obj',
                   'features':  ['t_rem', 'delay_bucket_1', 'delay_bucket_2',
                                 'delay_bucket_3', 'delay_bucket_4', 'delay_bucket_5', 'delay_bucket_6', 
                                 'time_since_last_call', 'shifts_available', 
                                 'sum_cutoff_at_start' , 'last_calls', 'time_by_shifts_available' ,'last_response',
                                 'cum_calls_made_at_start','cum_calls_made_0.9'],

                   },
              
              109: {'policy': 'xgb',
                   'search_files': False,
                   'runs' : 1,
                   'objective' : 'multi:softprob',
                   'eval_metric': 'rmse',
                   'ext': 'class_abs_norm_softprob_quant0.75' ,
                   'prob_threshold' : 0.75,
                   'action_type' : 'quant',
                   'normalize' : True,
                   'type': 'class',
                   'target': 'best_action',
                   'fit': False,
                   'criteria': 'check_obj',
                   'features':  ['t_rem', 'delay_bucket_1', 'delay_bucket_2',
                                 'delay_bucket_3', 'delay_bucket_4', 'delay_bucket_5', 'delay_bucket_6', 
                                 'time_since_last_call', 'shifts_available', 
                                 'sum_cutoff_at_start' , 'last_calls', 'time_by_shifts_available' ,'last_response',
                                 'cum_calls_made_at_start','cum_calls_made_0.9'],

                   },
              
              110: {'policy': 'xgb',
                   'search_files': False,
                   'runs' : 1,
                   'objective' : 'multi:softprob',
                   'eval_metric': 'rmse',
                   'ext': 'class_abs_norm_softprob_quant0.7', 
                   'prob_threshold' : 0.7,
                   'action_type' : 'quant',
                   'normalize' : True,
                   'type': 'class',
                   'target': 'best_action',
                   'fit': False,
                   'criteria': 'check_obj',
                   'features':  ['t_rem', 'delay_bucket_1', 'delay_bucket_2',
                                 'delay_bucket_3', 'delay_bucket_4', 'delay_bucket_5', 'delay_bucket_6', 
                                 'time_since_last_call', 'shifts_available', 
                                 'sum_cutoff_at_start' , 'last_calls', 'time_by_shifts_available' ,'last_response',
                                 'cum_calls_made_at_start','cum_calls_made_0.9'],

                   },
              
              
              204 : {'policy': 'corn',
                   'search_files': False,
                   'runs' : 1,
                   'ext': 'class_corn_0.25' ,
                   'learning_rate': 0.001,
                   'normalize' : True,
                   'type': 'class',
                   'target': 'best_action',
                   'wt':1000,
                   'fit': False,                   
                   'prob_threshold': 0.25,
                   'features':  ['t_rem', 'delay_bucket_1', 'delay_bucket_2',
                                 'delay_bucket_3', 'delay_bucket_4', 'delay_bucket_5',
                                 'delay_bucket_6', 'time_since_last_call', 'shifts_available', 
                                 'sum_cutoff_at_start' , 'last_calls', 'time_by_shifts_available' ,'last_response',
                                 'cum_calls_made_at_start','cum_calls_made_0.9'],
                   },
              
              205 : {'policy': 'corn',
                   'search_files': False,
                   'runs' : 1,        
                   'ext': 'class_corn_0.15' ,
                   'learning_rate': 0.001,
                   'wt':1000,
                   'normalize' : True,
                   'type': 'class',
                   'target': 'best_action',
                   'fit': False,
                   
                   'prob_threshold': 0.15,
                   'features':  ['t_rem', 'delay_bucket_1', 'delay_bucket_2',
                                 'delay_bucket_3', 'delay_bucket_4', 'delay_bucket_5',
                                 'delay_bucket_6', 'time_since_last_call', 'shifts_available', 
                                 'sum_cutoff_at_start' , 'last_calls', 'time_by_shifts_available' ,'last_response',
                                 'cum_calls_made_at_start','cum_calls_made_0.9'],
                   },
              
              206 : {'policy': 'corn',
                   'search_files': False,
                   'runs' : 1,
                   'ext': 'class_corn_0.2' ,
                   'learning_rate': 0.001,
                   'wt':1000,
                   'normalize' : True,
                   'type': 'class',
                   'target': 'best_action',
                   'fit': False,
                   
                   'prob_threshold': 0.2,
                   'features':  ['t_rem', 'delay_bucket_1', 'delay_bucket_2',
                                 'delay_bucket_3', 'delay_bucket_4', 'delay_bucket_5',
                                 'delay_bucket_6', 'time_since_last_call', 'shifts_available', 
                                 'sum_cutoff_at_start' , 'last_calls', 'time_by_shifts_available' ,'last_response',
                                 'cum_calls_made_at_start','cum_calls_made_0.9'],
                   },
              
              207 : {'policy': 'corn',
                   'search_files': False,
                   'runs' : 1,
                   'ext': 'class_corn_0.1' ,
                   'learning_rate': 0.001,
                   'wt':1000,
                   'normalize' : True,
                   'type': 'class',
                   'target': 'best_action',
                   'fit': False,
                   
                   'prob_threshold': 0.1,
                   'features':  ['t_rem', 'delay_bucket_1', 'delay_bucket_2',
                                 'delay_bucket_3', 'delay_bucket_4', 'delay_bucket_5',
                                 'delay_bucket_6', 'time_since_last_call', 'shifts_available', 
                                 'sum_cutoff_at_start' , 'last_calls', 'time_by_shifts_available' ,'last_response',
                                 'cum_calls_made_at_start','cum_calls_made_0.9'],
                   },
              
              111: {'policy': 'xgb',
                   'search_files': False,
                   'runs' : 1,
                   'objective' : 'multi:softprob',
                   'eval_metric': 'rmse',
                   'ext': 'class_abs_norm_softprob_quant0.3' ,
                   'prob_threshold' : 0.3,
                   'action_type' : 'quant',
                   'normalize' : True,
                   'type': 'class',
                   'target': 'best_action',
                   'fit': False,
                   'criteria': 'check_obj',
                   'features':  ['t_rem', 'delay_bucket_1', 'delay_bucket_2',
                                 'delay_bucket_3', 'delay_bucket_4', 'delay_bucket_5', 'delay_bucket_6', 
                                 'time_since_last_call', 'shifts_available', 
                                 'sum_cutoff_at_start' , 'last_calls', 'time_by_shifts_available' ,'last_response',
                                 'cum_calls_made_at_start','cum_calls_made_0.9'],

                   },
              
              208 : {'policy': 'corn',
                   'search_files': False,
                   'runs' : 1,
                   'ext': 'class_corn_mean',
                   'learning_rate': 0.001,
                   'wt':1000,
                   'normalize' : True,
                   'type': 'class',
                   'target': 'best_action',
                   'fit': False,
                   
                   'prob_threshold': 0.5,
                   
                   'features':  ['t_rem', 'delay_bucket_1', 'delay_bucket_2',
                                 'delay_bucket_3', 'delay_bucket_4', 'delay_bucket_5',
                                 'delay_bucket_6', 'time_since_last_call', 'shifts_available', 
                                 'sum_cutoff_at_start' , 'last_calls', 'time_by_shifts_available' ,'last_response',
                                 'cum_calls_made_at_start','cum_calls_made_0.9'],
                   },
              
              209 : {'policy': 'corn',
                   'search_files': False,             
                   'runs' : 1,
                   'ext': 'class_corn_0.3' ,
                   'learning_rate': 0.001,
                   'wt':1000,
                   'normalize' : True,
                   'type': 'class',
                   'target': 'best_action',
                   'fit': False,
                   
                   'prob_threshold': 0.3,
                   'features':  ['t_rem', 'delay_bucket_1', 'delay_bucket_2',
                                 'delay_bucket_3', 'delay_bucket_4', 'delay_bucket_5',
                                 'delay_bucket_6', 'time_since_last_call', 'shifts_available', 
                                 'sum_cutoff_at_start' , 'last_calls', 'time_by_shifts_available' ,'last_response',
                                 'cum_calls_made_at_start','cum_calls_made_0.9'],
                   },
              
              
              
              112 : {'policy': 'xgb',
                   'search_files': False,
                   'runs' : 1,
                   'objective' : 'binary:logistic',
                   'eval_metric': 'rmse',
                   'ext': 'class_abs_norm_binary_mean' ,
                   'normalize' : True,
                   'action_type' : 'sample',
                   'wt':1000,
                   'type': 'class',
                   'target': 'called', 
                   'prob_threshold': None,
                   'fit': False,
                   'criteria': 'check_obj',
                   'features':  ['t_rem', 'delay_bucket_1', 'delay_bucket_2',
                                 'delay_bucket_3', 'delay_bucket_4', 'delay_bucket_5',
                                 'delay_bucket_6', 'time_since_last_call', 'shifts_available', 
                                 'sum_cutoff_at_start' , 'last_calls', 'time_by_shifts_available' ,'last_response',
                                 'cum_calls_made_at_start','cum_calls_made_0.9'],
                   
                   },
              
              113 : {'policy': 'xgb',
                    'search_files': False,
                    'runs' : 1,
                    'objective' : 'reg:squarederror',
                    'eval_metric': 'rmse',
                    'ext': 'reg_abs_norm_mse_agg' ,
                    'type': 'reg',
                    'target': 'best_action',
                    'action_type' : 'round',
                    'normalize' : True,
                    'prob_threshold': None,
                    'fit': False,
                    'criteria': 'check_obj',
                    'features':  ['t_rem', 'delay_bucket_1', 'delay_bucket_2',
                                  'delay_bucket_3', 'delay_bucket_4', 'delay_bucket_5', 'delay_bucket_6', 
                                  'time_since_last_call', 'shifts_available', 
                                  'sum_cutoff_at_start' , 'last_calls', 'time_by_shifts_available' ,'last_response',
                                  'cum_calls_made_at_start','cum_calls_made_0.9'],
                    'scenarios': 3,
                    'aggregator': 'mean'

                    },#
              
              114 : {'policy': 'xgb',
                    'search_files': False,
                    'runs' : 1,
                    'objective' : 'reg:squarederror',
                    'eval_metric': 'rmse',
                    'ext': 'reg_abs_norm_mse_agg_min' ,
                    'type': 'reg',
                    'target': 'best_action',
                    'action_type' : 'round',
                    'normalize' : True,
                    'prob_threshold': None,
                    'fit': False,
                    'criteria': 'check_obj',
                    'features':  ['t_rem', 'delay_bucket_1', 'delay_bucket_2',
                                  'delay_bucket_3', 'delay_bucket_4', 'delay_bucket_5', 'delay_bucket_6', 
                                  'time_since_last_call', 'shifts_available', 
                                  'sum_cutoff_at_start' , 'last_calls', 'time_by_shifts_available' ,'last_response',
                                  'cum_calls_made_at_start','cum_calls_made_0.9'],
                    'scenarios': 3,
                    'aggregator': 'min'
                    

                    },#
              
              115 : {'policy': 'xgb',
                    'search_files': False,
                    'runs' : 1,
                    'objective' : 'reg:squarederror',
                    'eval_metric': 'rmse',
                    'ext': 'reg_abs_norm_mse_agg_wt' ,
                    'type': 'reg',
                    'target': 'time_to_wait',
                    'action_type' : 'round',
                    'normalize' : True,
                    'prob_threshold': None,
                    'fit': False,
                    'criteria': 'check_obj',
                    'features':  ['t_rem', 'delay_bucket_1', 'delay_bucket_2',
                                  'delay_bucket_3', 'delay_bucket_4', 'delay_bucket_5', 'delay_bucket_6', 
                                  'time_since_last_call', 'shifts_available', 
                                  'sum_cutoff_at_start' , 'last_calls', 'time_by_shifts_available' ,'last_response',
                                  'cum_calls_made_at_start','cum_calls_made_0.9', 'to_call'],
                    'scenarios': 3,
                    'aggregator': 'mean'    ,
                    'max_wait': 150,
                    'time_to_wait': 150,

                    },
              
              116 : {'policy': 'xgb',
                    'search_files': False,
                    'runs' : 1,
                    'objective' : 'reg:squarederror',
                    'eval_metric': 'rmse',
                    'ext': 'reg_abs_norm_mse_agg_wt45' ,
                    'type': 'reg',
                    'target': 'time_to_wait',
                    'action_type' : 'round',
                    'normalize' : True,
                    'prob_threshold': None,
                    'fit': False,
                    'criteria': 'check_obj',
                    'features':  ['t_rem', 'delay_bucket_1', 'delay_bucket_2',
                                  'delay_bucket_3', 'delay_bucket_4', 'delay_bucket_5', 'delay_bucket_6', 
                                  'time_since_last_call', 'shifts_available', 
                                  'sum_cutoff_at_start' , 'last_calls', 'time_by_shifts_available' ,'last_response',
                                  'cum_calls_made_at_start','cum_calls_made_0.9', 'to_call'],
                    'scenarios': 3,
                    'aggregator': 'mean'    ,
                    'max_wait': 150,
                    'time_to_wait': 45,

                    },
           
              
              # 113 : {'policy': 'xgb',
              #      'search_files': False,
              #      'runs' : 1,                    
              #      'objective' : 'reg:absoluteerror',
              #      'eval_metric': 'rmse',
              #      'ext': 'reg_abs_norm_time_to_wait' ,
              #      'normalize' : True,
              #      'action_type' : 'max',
              #      'type': 'reg',
              #      'target':'cum_calls_made',
              #      'train' : False,
              #      'fit': False     ,
                   
              #      'prob_threshold': None,
              #      'features':  ['t_rem', 'delay_bucket_1', 'delay_bucket_2',
              #                    'delay_bucket_3', 'delay_bucket_4', 'delay_bucket_5', 'delay_bucket_6', 
              #                    'time_since_last_call', 'shifts_available', 'last_response',
              #                    'sum_cutoff_at_start' , 'last_calls', 'time_by_shifts_available' ,'cum_calls_made_0.9'],
              #      },
          
          }
